---
- name: Ensure service
  service:
    name: '{{ swarm_client_service_file }}'
    state: '{{ swarm_client_service_state | default(omit) }}'
    enabled: '{{ swarm_client_service_enabled | default(omit) }}'
